.svench/svench.css
src/Form/Button.svelte
src/Form/Button.svench

New buttons added: including attention, warning, as well as new sizes.

feat: Updated button UI

---

.svench/svench.css
src/Form/Button.svelte
src/Form/Button.svench

feat: Updated button UI - Revert

---

src/Form/Select.svelte
src/Form/Select.svench
src/List/Items/ListItem.svelte
src/List/Items/ListItem.svench
src/index.js

Select element and ListItem Element

---

.svench/svench.css
src/Form/Input.svelte

Changes include:
New global text settings
Brand colors added and naming convention applied

feat: update to global css

---

src/Switcher/Switcher.svelte
src/Switcher/Switcher.svench

Adding a simple switcher component. This is quite a common one in the builder.

adding header switcher component

---

src/Form/Button.svelte

Light grey background added and text color changed.

feat: secondary button update to reflect mockups

---

src/Form/Button.svelte
src/Form/Button.svench

New colors added
New naming conventions
Disabled updated with new color vars

feat: Button update

---

src/Form/Button.svelte
src/Form/Button.svench

New colors added
New naming conventions
Disabled updated with new color vars

fix: Button update

---

src/Form/Input.svelte
yarn.lock

Tested via budibase builder, but not via svench :/ as i couldnt get it running on windows

fix(Input) - ability to set value with parameter

---

bbui
src/Form/Button.svelte
src/Switcher/Switcher.svelte

After the recent Budibase UI update, there are a few styling issues that require fixing. Hence this PR :-)

feat: button update and switcher enhanced

---

.svench/svench.css
src/Form/Button.svelte
src/Form/TextArea.svelte
src/Form/TextArea.svench

fix: text area fix , font fix, and button update

---

package-lock.json
package.json
src/DropdownMenu/DropdownMenu.svelte
src/DropdownMenu/DropdownMenu.svench
src/index.js

Note: I wrote the .svench file completely untested... as i cannot run svench.
Would appreciate some help testing that sometime

feat: added dropdown menu

---

.svench/svench.css
src/Styleguide/Spacing.svench

I've created a spatial system including a 4 pt grid for spacing and layout. Moving forward, this will improve control, consistency, and simplicity when implementing spacing within the Budibase builder.

feat: spatial system

---

src/DropdownMenu/DropdownMenu.svench
src/Form/Input.svelte
src/Form/Input.svench
src/Form/TextArea.svelte
src/Form/TextArea.svench

fixes button imports that hadn't been updated 🥳

fix: fixes button imports

---

src/DropdownMenu/DropdownMenu.svelte
src/DropdownMenu/DropdownMenu.svench

Dropdown UI update to match designs

fix: dropdown update

---

src/DropdownMenu/Popover.svelte
src/DropdownMenu/Popover.svench
src/Icons/Icon.svelte
src/Icons/icon-paths.js
src/index.js

Popover consists of the DropdownMenu component, with additional styling. This popover component is complete, but there is room for additional popovers with different variables.

feat: Popover

---

src/Button/Close.svelte
src/Button/Close.svench

https://www.loom.com/share/6f9ad0c8d7fb4e30a5e21333831ca986
#92 
I have created a close button component. It will be used within the modal and possibly popover.

feat: close button

---

src/Button/TextButton.svelte
src/Button/TextButton.svench
src/Icons/Icon.svench
src/Icons/icon-paths.js

- Icon for group by
- Active prop for text button to make sure it stays highlighted even when it isn't hovered

fix: adding group icon and active prop for textbutton

---

src/Form/Input.svelte
src/Form/Select.svelte
src/Form/TextArea.svelte
src/Form/TextArea.svench
src/Form/Toggle.svench

Accidently added this to the wrong branch but it should merge just fine :)

fix: Input, Select, TextArea and Toggle no longer warn about missing props

---

src/Button/TextButton.svelte
src/Button/TextButton.svench

`<TextButton>` did not accept any colours ... e.g. `<TextButton blue> Add Action </TextButton>`
So I added them. Please correct me if we dont want this, and I should just create a custom text button in the builder, for my use case.
I also changed the svench to import TextButton as "TextButton" instead of "Button".... as i initially was confused by this

feat: Text button colours

---

src/DropdownMenu/DropdownMenu.svelte
src/Form/Select.svelte
src/Form/Select.svench
src/Modal/Modal.svelte

https://www.loom.com/share/4fe76809071d4f03925ef0e41ddf26b5
Ability to free type into a select... usage
```
<Select editable >
....
</Select>
```
When a dropdownMenu was used inside a modal, it was positioned way on the other side of the screen
Modal had a min height and width - this was causing content to something not fit, or scroll unecessarily

feat: editable select + some fixes

---

package-lock.json
package.json
rollup.config.js
src/DatePicker/DatePicker.svelte
src/DatePicker/DatePicker.svench
src/index.js

Date picker component using flatpickr.
Will be used in the builder and in standard-components.

feat: datepicker

---

src/Form/DataList.svelte
src/Form/DataList.svench
src/index.js

Moving the editable select out into it's own datalist component

feat: move editable select into its own component

---

src/Dropzone/Dropzone.svelte
src/Dropzone/Dropzone.svench
src/Dropzone/fileTypes.js
src/Icons/Icon.svench
src/Icons/icon-paths.js

Now that the dropzone component is being used by both the apps and the builder, I decided to abstract out into a BBUI component.
- Takes props for processing files and a handler for the file exceeding the recommended size. Both of these are controllable via props

feat: dropzone component moved into bbui

---

.svench/svench.css
src/Button/Button.svelte
src/Form/Input.svelte
src/Form/Input.svench
src/Form/Select.svelte
src/Links/Home.svelte
src/Styleguide/Body.svelte
src/Styleguide/Heading.svelte
src/Styleguide/Label.svelte
src/Styleguide/Typography.svench

- Typography component updated - default line-height removed and is now a prop (lh)
- Underline removed from a tag
- Inputs reduced in size and aligned with other inputs
- Select component radius and font updated
- New input style added

fix: components updated with new styles

---

src/Button/Button.svelte

fix: primary and secondary button updated with border var

---

.editorconfig
src/Form/Multiselect.svelte
src/Form/Multiselect.svench
src/index.js

This add a `Multiselect` component, which allows selecting multiple values from a dropdown.
Features:
- Interchangable with `Select` due to identical HTML
- Automatic sizing to fit options
- Text overflow handling
- `font-size-xs` always to maximise space
- Options list scrollable if it would be off screen
Default style:
Secondary style:
Outline style:
Disabled style:

Multiselect component

---

src/Form/Multiselect.svelte

Improves the binding of the value to the UI to avoid edge cases where stale UI would appear.

fix: improve binding of multiselect value to prevent stale UI

---

.svench/svench.css
src/Button/Button.svelte
src/Form/Input.svelte
src/Form/Input.svench

When designing the new auto screens for BB apps, it was evident we needed new inputs - larger and more specific to our needs. We added the following props:
Presentation input added for viewing purposes
Border and large props added for UX within BB apps
https://www.loom.com/share/2d94edeca5814d23a0654d99eb8d7d95

feat: inputs for autoscreens

---

src/Button/Button.svelte
src/Button/Button.svench

Adds a new button style which works on light or dark backgrounds.

feat: add translucent button which works on light and dark backgrounds

---

.svench/svench.css
src/Button/Button.svelte
src/Button/TextButton.svelte
src/DropdownMenu/DropdownMenu.svelte
src/Dropzone/Dropzone.svelte
src/Form/DataList.svelte
src/Form/Input.svelte
src/Form/Input.svench
src/Form/Multiselect.svelte
src/Form/Select.svelte
src/Form/Toggle.svelte
src/Icons/Icon.svelte
src/Modal/Modal.svelte
src/Modal/ModalContent.svelte
src/Popover/Popover.svelte
src/Styleguide/Body.svelte
src/Styleguide/Borders.svench
src/Styleguide/Color.svench
src/Styleguide/Heading.svelte
src/Styleguide/Label.svelte

Just doing a release because my previous PR didn't trigger one.

feat: very semantic much release

---

src/Form/Slider.svelte
src/Form/Slider.svench

This adds a slider component. Cross browser styles for webkit and firefox have been implemented, but not for IE (stop using IE).

feat: add slider

---

src/index.js

Forgot to actually export the Slider component 🤷‍♂️

fix: export Slider component

---

public/index.html
src/Drawer/Drawer.svelte
src/Drawer/Drawer.svench
src/index.js

feat: adds Martins BottomDrawer (now Drawer) for easy re-usability across the project

feat: adds Martins BottomDrawer for easy re-usability across the project

---

src/Drawer/Drawer.svelte
src/Drawer/Drawer.svench
src/actions/click_outside.js
src/index.js

Also exposes the actions to the consumer

fix: corrects some drawer issues

---

.svench/svench.css
src/Form/Input.svelte
src/Form/Input.svench

Some inputs had a 1px border, and a 2px hover/focus border causing them to increase in size and disturb the UI

fix: border width fixed on inputs

---

src/Drawer/Drawer.svelte

- drawer width updated
- position changed
- border added

fix: drawer update to contain the drawer withing the preview area

---

src/Popover/Popover.svelte

This switches the Popover to use the positionDropdown action instead of it's own logic

feat: popover now uses action instead of internal logic

---

src/Form/Checkbox.svelte
src/Form/Checkbox.svench.svx
src/Form/Radio.svelte
src/Form/Radio.svench.svx

Centers the label text in the Radio and Checkbox components

fix: center label text in Radio and Checkbox components

---

src/Form/Input.svelte
src/Form/Select.svelte
src/Styleguide/Body.svelte
src/Styleguide/Heading.svelte

improved border consistency across inputs
increased the darkness of the grey in body and heading

fix border and input grey enhancements and consistency
