.github/workflows/release.yml
S3 files did not have public access when deployed - hence 403s 
This also
- deletes old build files from the bucket
- "fixes some weird symbolic link problems that may come up." (https://github.com/jakejarvis/s3-sync-action)
=> fix: updated GH Action to set S3 files to public read

src/Form/Select.svelte
2 dropdown arrows are appearing on a select...
=> fix(select): hiding default arrow on win

src/Modal/Modal.svelte, src/Modal/Modal.svench
the `width` was set, and was stopping the Modal to grow to it's `max-width`. removed this, and added an exmple of how to use the `maxWidth` property
=> fix: removed width, so we can set maxWidth via prop

src/Modal/Modal.svelte, src/Modal/Modal.svench, src/index.js
Adding minWidth to modal
Adding Spacer to exports
=> fix: adding min-width prop to modal & adding Spacer component to exports

.gitignore, src/Form/TextArea.svelte
Don't render the outermost label component when neither a label or the "edit" prop are specified. This removes the whitespace that currently exists when neither prop are specified.
Also just adds webstorm config to gitignore.
=> fix: don't render empty textarea labels

src/Modal/Modal.svelte, src/Modal/Modal.svench
Added a default padding to Modals.
If we need custom padding, we can use `<Modal noPadding> ... </Modal>`,  the set the padding on the content
=> fix: reinstated default padding to modal

src/Form/Input.svelte, src/Form/Input.svench
This makes inputs respect `type="number"`. Rather than outputting a string value, binding to the value of an input with `type="number"` will actually bind a numerical value. The default empty state has not been changed however to maintain consistency, and as such is still an empty string `""`.
=> feat: allow inputs to respect type=number

src/Form/Input.svelte
Lesson learned here is that svelte components can have multiple handlers for the same event without overriding each other.
For example the following allows binding to native `on:change` events, as well as firing a custom handler.
```
...
on:change
on:change={handler}
...
```
This was the case in the `Input` component and I removed the first `on:change` handler thinking it was redundant and would just be overridden by the second one as typical prop overriding would work.
Lesson learned!
=> fix: add back in event handlers that were removed by mistake

src/Form/Input.svelte
Another tiny magic bug which was not appearing in the svelte REPL. It's such an edge case but...
If you `bind:value` to 2 different components, 1 `Input` and 1 `TextArea`, clearing the `TextArea` somehow sets a value of `undefined` to the `Input`, overriding the default prop and showing the literal string `undefined` in the `Input`. Attempting this manually with any combination of `null` or `undefined` value props to the input fails to reproduce it but anyway, this will just ensure nullish values can never be rendered.
Previously there was a similar statement to this but it was checking for falsiness via `||` which would have now failed anyway to be fair, due to numerical 0 now being a potential value.
=> fix: render nullish input values as empty string

.svench/svench.css
Replacing incorrect css variables from `--font-size-lg` and `--font-size-md` to `--font-size-l` and `--font-size-m` respectively. `h5` elements are used extensilvely in the builder and currently these incorrect variables are causing inconsistencies in sizing.
=> fix: incorrect font-size css variables for h5 and h6 elements

.svench/svench.css, public/index.html, rollup.config.js, src/DatePicker/DatePicker.svelte, src/DatePicker/DatePicker.svench, src/Form/DataList.svelte, src/Form/DataList.svench, src/Form/Input.svelte, src/Form/Select.svelte, src/Form/Select.svench, src/Form/TextArea.svelte, src/Form/TextArea.svench, src/Form/Toggle.svelte, src/Form/Toggle.svench, src/Styleguide/Label.svelte
This PR standardises styles for all form components and a few others - bringing them all in line with each other. The components affected are: `Input`, `Select`, `TextArea`, `DataList`, and `DatePicker`. `Toggle` has also been updated to at least respect font sizes although its usage is minimal currently. `Label` margin bottom has been reduced from `--spacing-m` from `--spacing-s` to couple better visually with components using them.
These changes provide the following consistencies between these components:
- All render with default font size of `--font-size-s` (14px)
- All accept a `thin` prop to change the font size to `--font-size-xs` (12px)
- All accept a `label` prop with identical styling
- All correctly display `:focus` styling accross browsers `border: var(--border-blue)` (2px …
=> feat: standardise form styles

src/Form/Select.svelte
Select labels were rendered top level, but really should be inside a parent container so that they work nicely in grid layouts, the same as the other components.
=> fix: wrap select and its label inside single parent

src/Form/TextArea.svelte
Text areas should definitely have an `on:change` handler. This adds it.
=> feat: add onchange handler to textarea

src/Form/Toggle.svelte
Toggles should have an `onchange` handler. This adds it.
=> feat: add onchange handler to toggles

src/Form/Input.svelte
Fixes the accidental rename of `display` CSS properties to `presentation`.
=> Fix input flex CSS properties being renamed to presentation

src/Form/DataList.svelte, src/Form/DataList.svench, src/Form/Input.svelte, src/Form/Input.svench, src/Form/Multiselect.svelte, src/Form/Multiselect.svench, src/Form/Select.svelte, src/Form/Select.svench, src/Form/TextArea.svelte, src/Form/TextArea.svench, src/List/Items/DetailSummary.svelte, src/List/Items/DetailSummary.svench
This PR adds `extraThin` props to all form components which reduces vertical padding. This will be used heavily in the frontend section of the builder to display settings and design options in a compact form.
This also changes DetailView styles to be more flexible.
=> feat: smaller size options

src/Popover/Popover.svelte
Adds `show` and `hide` events to popovers so other components can be kept aware of their state. This is required for things like the new component dropdowns - where we want to be aware of when the popover is closed to undo the "active" styling of the category the user had open.
=> feat: add show and hide events to popovers

src/Form/TextArea.svelte
Adds a `getCaretPosition` function to the text area component which can then be used to input text (like binding values) into the text area wherever the caret is.
=> feat: add caret position function to text area.

src/Form/Multiselect.svelte
Reactive declarations on the multiselect were causing some problems in the builder. This PR allows us to listen to `on:change` for the multiselect for a bit more control
=> fix: multiselect component change event capability

src/Button/Button.svelte
This PR ensures button borders (except text buttons) are always fixed at the standard 2px width. This prevents button heights changing when toggling between different button states or colours, which in turn prevents weird jumping issues in containers which contain buttons.
=> fix: standardise all button border widths
